name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel # required for jupyter notebook in VS Code
  - pytest
  - pip  # if you need more packages installed from pip 
  - pip:
    - emoji
